# Generated by Django 5.1.1 on 2024-11-28 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_student_phone_alter_student_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=20)),
                ('category', models.IntegerField(max_length=20)),
                ('price', models.IntegerField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
