# Generated by Django 5.1.1 on 2024-11-28 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_post_delete_buyer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Message',
        ),
    ]
