# Generated by Django 5.1.1 on 2024-11-28 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_post_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='created_at',
        ),
    ]
