# Generated by Django 5.1.1 on 2024-11-28 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_message_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='category',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='categories',
            name='price',
            field=models.IntegerField(),
        ),
    ]
