# Generated by Django 5.1.1 on 2024-11-28 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_categories_category_alter_categories_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='product_name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
